### ISSUE TITLE
Binary Prefixes (MebiByte, KibiByte etc.)

### ISSUE THREAD

**Issue by JohannesRudolph** [unitsofmeasurement/uom-systems#116]
I'm not sure if this is something supported by UCUM, but we are very interested in using the UOM library for unit conversions involving SI-kilo bytes (1000 bytes) vs. Mebi-Bytes (1024 bytes, 2^10). I tried adding a prefixed unit to UCUM, but of course it has troubles with the formatter. What is the recommended way to add support for this? 

Is there a 10^1024 base unit in the UCUM spec already?

**Comment by keilw** [comment]
Not in UCUM, because that's not in the UCUM spec as you mentioned, but in a companion library called [uom-lib-common](https://github.com/unitsofmeasurement/uom-lib/tree/master/common) This was mainly due to making it usable in both Java ME Embedded (via the 1.0 RI) and Java SE 8 (via uom-se).
In version 2.0 it is possible, those prefixes go to a different place e.g. the new RI Indriya, but at least they should implement a newly proposed Prefix: https://github.com/unitsofmeasurement/unit-api/issues/34

**Comment by keilw** [comment]
Also see https://github.com/unitsofmeasurement/indriya/issues/26, will close this ticket now, please follow up in the API or RI
