### ISSUE TITLE
It would be nice if there was a way to disable for UCUMFormat the special symbols for “square inch,” “cubic foot,” etc. as they are deprecated

### ISSUE THREAD

**Issue by mattdehring** [unitsofmeasurement/uom-systems#137]
Per [http://unitsofmeasure.org/ucum.html#para-34](§34 international customary units) annotation 4 the custom symbols [sin_i], [sft_i], [syd_i], [cin_i], [cft_i], [cyd_i] have been deprecated and  [in_i]2, [ft_i]2, [yd_i]2, [in_i]3, [ft_i]3, [yd_i]3 should be preferred. It would be nice if there was a way to switch those symbols off. Optimally it would still be able to parse them but formatting them would output the exponent version.

**Comment by keilw** [comment]
Should they be disabled with a new release or do you see a need to switch between either generation without using a different version of this module?

**Comment by mattdehring** [comment]
For my project it would be fine if they were just disabled as we don't have any existing code to handle. To me it is more of a question of how backwards compatibility should be handled. Best case it would be able to parse both and there was a flag to set or to have separate properties files that would enable or disable the formatting.

**Comment by keilw** [comment]
Guess "deprecated" means they should be replaced by the exponent form. It would be cumbersome to add an artificial alias for parsing only, the `UCUMFormat` usually works both ways, at the moment alias() can't be applied because those formatters are based on Java Resource Bundles. While there are some tutorials on [Resource Bundle Control](https://docs.oracle.com/javase/tutorial/i18n/serviceproviders/resourcebundlecontrolprovider.html) most sources agree, Resource Bundles are not meant for dynamically updating values at runtime. Neither is the UCUM catalog meant to be tweaked or extended at runtime, as other `UnitFormat` implementations like `SimpleUnitFormat` allow you via `label()` or `alias()`.

**Comment by keilw** [comment]
Deprecating them for now, we may remove them completely in a follow-up version.
