### ISSUE TITLE
Units in `USCustomary` missing labels and/or name

### ISSUE THREAD

**Issue by GregJohnStewart** [unitsofmeasurement/uom-systems#193]
There are a number of static units that are missing name and symbol values. I can probably go in and add them myself and make a PR, but wanted the consensus/ go-ahead from you guys first.

Examples (from the units I currently directly use):

- `USCustomary.INCH`
- ...

There are way more, seems like most of the ones I use are missing at least their symbol or name.

**Comment by keilw** [comment]
I can't see why all the reflection would be necessary? Maybe @desruisseaux gets some ideas from that or how it could be used?

Also please point units in USCustomary that do not already have both symbol and name via `private static <U extends Unit<?>> U addUnit(U unit, String name, String label)` ?

`INCH` is probably a rare exception where only the symbol is added,

**Comment by desruisseaux** [comment]
I did not verified in source code, but the call to `setAccessible(true)` suggests that the purpose of the reflection is to read a private field.

**Comment by keilw** [comment]
neither "name" nor "symbol" are private at least not where extensions to `AbstractSystemOfUnits` call the existing `addUnit()` method.
If say the name of `INCH` is missing, we can add that based on an issue (including this one) but I fail to understand how the code snipped made sense because it more or less reinvents pretty much everything `USCustomary` already declares.

**Comment by GregJohnStewart** [comment]
@keilw Reflection is necessary as a direct user of the api, unless there is an easier way. I am unaware of any way to set name or symbol after the object is created. If there is an easy way to copy a unit object while specifying name/symbol I'd like to know.

I'm fairly certain name and symbol are private fields; their getters are not private.

At any rate, all that reflection is my personal workaround until all the original static units get updated with proper name/symbols.

**Comment by keilw** [comment]
@GregJohnStewart Yes `Unit` is supposed to be immutable, and the symbol is only for a small fraction of units because **Transformed units have no symbol**. That's where the label comes into play, putting a symbol on them goes against parts of the framework especially formatting and you may get strange results trying to format a `TransformedUnit` where you put a symbol on it via reflection.

**Comment by GregJohnStewart** [comment]
I would normally accept that transformed units have no symbol, etc, but in this case we are specifically describing standardized units. A user of the library expects these to be fully described. If the units aren't fully described, then that makes the library much less helpful and usable.

Also, through my testing it looks like the transformed units do actually keep their dimensions:
`Testing unit: in, name="Inch", symbol="in", dimension="[L]"`

**Comment by keilw** [comment]
That depends on how they are transformed or multiplied, if INCH was derived by multiplying or dividing METRE then of course the dimension is kept the same, otherwise it would be something else like "[L]/...", but except those that are explicitly `Dimensionless` all units are supposed to have a dimension.

The units are fully described and "label" in this case is a more flexible visual representation while only certain units like base units have a symbol. The standard is based around such principles therefore changing that would be at everyone's risk, there are several assumptions like formatting based on that, so the symbol has a more narrow purpose while every unit must produce a label, even if it may be a blank string for very special cases.

**Comment by GregJohnStewart** [comment]
So the unit formatting makes sense, but raises the question of why are name/symbol included in the first place then?

Also, having a little trouble nailing down where a formatter exists to get the name/symbol strings from a given Unit, happen to have a point to get this functionality?

**Comment by keilw** [comment]
Now all units in `USCustomary` have names, for additional options of `SimpleUnitFormat`, etc. please raise another ticket for the RI.
