### ISSUE TITLE
UCUM: some results like "m/s" are not formatted correctly

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-systems#21]
In https://github.com/unitsofmeasurement/uom-systems/blob/master/ucum-java8/src/test/java/systems/uom/ucum/format/UnitFormatTest.java some format tests fail because METER.divide(SECOND) becomes "1/s.m" instead of "m/s"

**Comment by keilw** [comment]
Use https://github.com/unitsofmeasurement/jackson-module-unitsofmeasure/issues/4 to verify

**Comment by magnonasc** [comment]
@keilw I'll take a look on this today, you can assign it to me if you want

**Comment by keilw** [comment]
Thanks, I invited both @magnonasc and @garretwilson to the @adopters team. Don't be bothered by the name, it is from the time of "adopting the JSR" as opposed to @experts who are members of the EG. Maybe I'll reconsider the naming of some teams, but that'll do to assign you tasks.

**Comment by magnonasc** [comment]
I fixed the problem for this unit type in a commit that I'll make a pull request when I get rid of the end of line problem again.. BUT, it's good to mention that the formatter is not fixed at all, I saw that there's the following statement on the code:
```
else {
  app.append('/');
  pow = -pow;
}
```

This is a problem, because if you have something in the quocient already e.g., `.../unit1` you'll want to just multiply it e.g., `.../unit1 . unit2` and not keep adding `unit1/unit2/unit3/...` in all cases, so even if it's suitable for the formatting needs at the moment we'll have to keep an eye at this, I'm sure there'll be a case where it'll give an error in the future.

**Comment by magnonasc** [comment]
It's fixed for `m/s`, but in the future we might get back to test this formatter to other composed units.
