### ISSUE TITLE
How to add new symbols for parsing

### ISSUE THREAD

**Issue by krevelen** [unitsofmeasurement/uom-systems#48]
The following parse command fails, probably due to a missing `Units#addUnit(Unit)` call for `Units#DAY`:
```java
Quantities.getQuantity( "300 "+Units.DAY.getSymbol() );
```

**Comment by keilw** [comment]
It's not that simple, since `DAY `is a derived unit, `getSymbol()` by definition may either return `null `or another symbol, e.g. that of the base unit (`SECOND `in that case). I'm afraid this is not an issue for uom-system either, but as an ad-hoc workaround, if you call `SimpleUnitFormat.getInstance().label(Units.DAY, "d")` that should work. If there was another issue parsing the quantity, will look into that.

**Comment by keilw** [comment]
It actually works, see https://github.com/unitsofmeasurement/uom-demos/blob/master/console/systems/common-java8/src/main/java/tec/uom/demo/se/systems/common/CommonFormatDemo.java
