### ISSUE TITLE
Create a .gitattributes file for the project and normalize end of line formats

### ISSUE THREAD

**Issue by magnonasc** [unitsofmeasurement/uom-systems#66]
After pushing changes for `UCUM` class I noticed that the whole class was appearing as modified on the commit, which was caused by the end of line used by the project, which was set up to CRLF for UCUM stuff.

It seems that this project is using CRLF in the remote repository itself only for the UCUM module, which means that developers would have to set `core.autocrlf` differently for this module, but that's a global setting and it interferes with the other modules.

The best solution is to create a `.gitattributes` file to normalize all the files being commited to the repository to put them on the same end-of-line format, which would be LF (the most used on the repository). This issue will take a single file with a single line to be done, and it will solve problems like a whole file showing up as edited on the pull requests when you change a few lines, for example.

See https://help.github.com/articles/dealing-with-line-endings/

**Comment by keilw** [comment]
We have not had these kinds of problems before and at least many contributors must be using either Windows, Mac or both. I assume @magnonasc works on Linux or Unix most of the time? 
After accepting the invitation to @unitsofmeasurement/adopters you should both be able to push directly or merge (e.g. each other's PR if everything works)

**Comment by magnonasc** [comment]
I'm working on Windows only, but the problem is that if a part of the project is using LF and the other CRLF it means that someone commited files over Linux or Unix **and** Windows without care to this problem.

**Comment by garretwilson** [comment]
You're already having this problem. If you download the `.zip` file of your repository, you'll notice that the UCUM files (so @magnonasc  tells me) have CRLF line endings, but the rest have LF line endings. If `core.autocrlf` was set on your system, it would have prevented this. But that's a global setting, so it's hard to work with settings on different projects. A `.gitattributes` file will do the same, but on a per-project basis.

We found this out because we normalize the GlobalMentor repository files using `LF` in the repositories, but we check out on Windows using CRLF. We use `.giattributes` files, but we set `core.autoclrf` as a backup in case (like this project) someone doesn't have a `.gitattributes` file.

So what happened is that most of the files in this project checked out fine, converting LF (in the repository) to CRLF (on Windows). The UCUM files were already in CRLF format. But when @magnonasc  got ready to check in files, his `core.autocrlf` setting tried to change the CRLF back to LF for the UCUM files, but they were in the repository as CRLF, so Git said that all the lines were changed. (He had to make a temporary `.gitattributes` file to keep Git from converting the line endings back when he did his earlier commit.)

If it's been working for you so far, you've just been lucky that no developer has had `core.autocrlf` set, and their text editors haven't done any conversions. But the minute someone converts to their local platform and checks the files back in, the diffs will go crazy.

The nice thing is that adding a `.gitattributes` file will tell the Git client to do all the conversions automatically, but @magnonasc  will need to normalize all the UCUM line endings to LF (as they should have been anyway) to make this all work. I's all explained in the links I gave in #69 --- but I recommend reading them with a beer or maybe even tequila handy. haha 😉

**Comment by keilw** [comment]
That is possible because part of the sources especially .properties files emerged from different codebases like JScience 5 and a few could also have been derived from Eclipse UOMo.

**Comment by keilw** [comment]
Guess it won't apply from there like Parent POM settings, but ideally a proper .gitattributes file should also be placed in https://github.com/unitsofmeasurement/uom-parent as a template and starting point for new repos and all repositories that might use it.

**Comment by magnonasc** [comment]
This issue was fixed and probably there'll be no more problems with diff showing a whole file edited while there's just some of them changed.
