### ISSUE TITLE
Clarification of equivalence of UCUM "L" and "l".

### ISSUE THREAD

**Issue by garretwilson** [unitsofmeasurement/uom-systems#82]
I'm opening this issue for a definitive clarification on whether UCUM in case-sensitive mode considers `"L"` and `"l"` to be the same unit, or distinct units that are nonetheless convertible with a 1:1 correspondence.

To put this in practical terms, consider the following test case (using JUnit with Hamcrest):

```java
UnitFormat ucumUnitFormat;  //TODO get unit format for "UCUM"
Unit liter1 = ucumUnitFormat.parse("l");
Unit liter2 = ucumUnitFormat.parse("L");
assertThat(liter1, is(equalTo(liter2)));
```

Should this test pass or fail? Are the units represented by "l" and "L" the same unit? (I would think that knowing the answer is essential for @magnonasc 's work in finishing UCUM implementation.)

Note that at https://github.com/unitsofmeasurement/uom-systems/issues/4#issuecomment-284885795 @keilw seems to indicate indicated that the above test should _fail_, because he says that they are "two different distinct units".

I have opened up [UCUM Track ticket 195](http://unitsofmeasure.org/trac/ticket/195) to get a definitive answer from UCUM, but they haven't responded unfortunately.

So what definitively should be the outcome of the above unit test according to UCUM? Or do we even know?

**Comment by keilw** [comment]
Most importantly this depends on which variant of `UCUMFormat` you apply. The UCUM system only has one LITER entry so far, that creates a pickle, but how about either a `UCUM.CUBIC_DECIMETER` or `UCUM_LITER_DM3`? If you check the definition unit in http://unitsofmeasure.org/ucum.html#iso1000 one is equal to `1 dm³` the other to `1 l`. Guess we must declare them separately in the UCUM system. `CUBIC_DECIMETER` could simply refer to `DECI(Units.CUBIC_METRE)`. WTYT?

**Comment by magnonasc** [comment]
I changed the variables to:
```
    /** As per <a href="http://unitsofmeasure.org/">UCUM</a> standard. */
    public static final Unit<Volume> LITER_CI = addUnit(DECI(Units.CUBIC_METRE));

    /**
     * As per <a href="http://unitsofmeasure.org/">UCUM</a> standard.
     * <p>
     * This unit refer to {@link #LITER_CI}
     * </p>
     */
    public static final Unit<Volume> LITER_CS = addUnit(LITER_CI);
```
and the following unit tests keep working (but one of them should not):
```
    @Test
    public void testParseUCUMCSLowercaseLiter() {
        final UnitFormat format = UCUMFormat.getInstance(CASE_SENSITIVE);

        assertEquals(LITER_CS, format.parse("l"));
    }

    @Test
    public void testParseUCUMCSUppercaseLiter() {
        final UnitFormat format = UCUMFormat.getInstance(CASE_SENSITIVE);

        assertEquals(LITER_CS, format.parse("L"));
    }
```
Any idea of why?

**Comment by keilw** [comment]
It seems OK for testing, but I would really not irritate people by putting the CS or CI names into the actual unit.

**Comment by magnonasc** [comment]
For what I read in `UCUM` docs, the `CASE_SENSITIVE` of `LITER` should just refer to its `CASE_INSENSITIVE`, as its both entries were created to just allow the `CASE_SENSITIVE` to have 2 forms... Maybe the best solution for that is to just not have a `CASE_SENSITIVE` variant for that

**Comment by garretwilson** [comment]
At first I too thought that UCUM made `L` and `l` the same unit, but after @keilw indicated that they were distinct in UCUM, I thought about it further. Now I'm starting to agree with @keilw .

Take a look at some of the other UCUM units. In UCUM a "Maxwell" (`Mx`) is defined as `1 Wb`, and a "weber" (`Wb`) is defined as `1 V.s`. But we don't think that `Mx` and `Wb` are the same units. They are _equivalent_ in that if I convert `1 Mx` to `Wb` then I get `1 Wb` and not `23 Wb`. But they are distinct units.

Analogously I'm forced to read the UCUM as saying that if I (in case-sensitive mode) convert `1 L` to `l` then I will get `1 l`, but that `L` and `l` are nonetheless distinct units, as @keilw said already.

Then the question becomes which representation is _preferred_ or "canonical" for "liter". I see that the case-insensitive version is listed as `L`. (Plus all the examples show `L`, `mL`, etc.) This leads me to believe that the canonical UCUM representation for liter is `L`.

I think we should define the constant to be identical to the name listed in the UCUM. Thus I think there must be a canonical unit `LITER` with a representation `L` and equivalent to `1 l` . From the above reasoning I think that in addition there must also be _another_ unit (perhaps `LITER_COMPATIBILITY`) with a representation `l` and equivalent to `1 dm3`. Again all of this is directly analogous to `Mx` and `Wb`; whatever you do for those two, you must also do for `L` and `l`, to stay consistent with the UCUM.

(None of this precludes there being a "canonicize" method to convert `l` to `L`, for example; but this is outside the scope of both JSR 363 and UCUM. See https://github.com/jmandel/ucum.js/issues/9#issuecomment-286115555 for example.)

Lastly I want to say that it is _imperative_ that the following work:

```java
UnitFormat ucumUnitFormat;  //TODO get unit format for "UCUM"
assertThat(ucumUnitFormat.format(ucumUnitFormat.parse("L")), is("L"));
```

And to answer my original question in this ticket, I now think that the following should _fail_:

```java
UnitFormat ucumUnitFormat;  //TODO get unit format for "UCUM"
Unit liter1 = ucumUnitFormat.parse("l");
Unit liter2 = ucumUnitFormat.parse("L");
assertThat(liter1, is(equalTo(liter2)));
```

**Comment by garretwilson** [comment]
> The UCUM system only has one LITER entry so far, that creates a pickle, but how about either a `UCUM.CUBIC_DECIMETER` or `UCUM_LITER_DM3`?

Those would work, too. (I would lean toward one that begins with `LITER_…`.) I'm not _too_ concerned about what we name the other one, as long as the canonical one is named `LITER`.

**Comment by keilw** [comment]
I tried calling it the latter, have not committed, but I wanted to try out mentioned tests.

**Comment by magnonasc** [comment]
Fixed as part of commit 028c73a

**Comment by garretwilson** [comment]
I want to reopen this issue so that we can ponder the ramifications of the latest I have heard from the UCUM.

Earlier in this ticket I had agreed with @keilw that the UCUM specification seems to indicate that in case-sensitive mode, `l` and `L` are distinct unit. But today someone from the UCUM group finally replied to ticket http://unitsofmeasure.org/trac/ticket/195 and the situation is even murkier than it appears. Let me try to explain my current understanding.

First of all the UCUM seems to think of units as values equivalencies. This particular represented seemed confused as to why we would even want to distinguish among equivalent units. Thus a `uL` and a `nst` were all equivalent measurements and the UCUM would understand both of those meaning the exact same thing.

Of course that won't work in the real world, when a user wants to work with liters but we switch to steres. But from the discussion, the impression I got is that UCUM intends `l` and `L` to be synonyms, even in case-sensitive mode! They specifically said:

> l and L are synonyms, yes. The Europeans tend to write l and the Americans tend to write L. The standard we were based on allowed both, so we kept with that.

The best I can understand all this is that if we want to keep track of different units, we must have special logic that will understand that both `l` and `L` refer to the same unit "liters". In other words, regardless of what the specification tables (and the XML file) say, UCUM seems to consider `l` and `L` a special case that is always case-insensitive.

This interpretation would remove the need to have a separate liters constant, but it would also require the parser to have special processing in case-sensitive mode to map both `l` and `L` to "liter".

@keilw and @magnonasc , what do you think after reading the UCUM discussion?

**Comment by keilw** [comment]
Running e.g. https://github.com/eclipse/uomo/blob/master/examples/ucum/org.eclipse.uomo.examples.ucum.console/src/main/java/org/eclipse/uomo/examples/ucum/console/UcumDemo.java in the UOMo UCUM examples, I recall both `System.out.println(service.analyse("l"))` and `System.out.println(service.analyse("L"))` give a result. While printing (regardless of 1 or 2 `LITER` constants, the problem in https://github.com/unitsofmeasurement/uom-systems/issues/97 occurs with both of them) has problems, the `UCUMFormatParser` works extremely well so far. Despite being originally generated and therefore ugly to read. I could imagine something along the lines of `SimpleUnitFormat.alias()` (currently not in `AbstractUnitFormat`) where you explicitly define `LITER.alias("L")` and it could be controlled if it only works for parsing (in `SimpleUnitFormat` it also does) However, `UCUMFormatParser` is rather delicate, so it may not be trivial to add it without possible side-effects or missing something. As C/I and C/S are always distinct and the distinction works fairly well for the parsing parts, I would not like to compromise that by saying "here C/S is the same as C/I". We got bigger issues if we wanted to get print/format work for every single UCUM unit.

**Comment by keilw** [comment]
I would try to make the semi-standard mechanism of `alias()` available to `UCUMFormat`.  While it is not part of the API (unlike `label()`) there were thoughts about adding it, and with enough good reasons we might in a future JSR version. `alias()` just hits the point here because that's what it is based on the UCUM committer's response.

**Comment by keilw** [comment]
@garretwilson @magnonasc Under the assumtion to remove STERE until further notice, are you happy to keep LITER and LITER_DM3 in the system like they are?

**Comment by garretwilson** [comment]
At this point I just want the unit tests to pass. Do whatever you guys need to do to un-break it so that the implementation works with the most basic of SI and English units.

When I committed resources to this project to finish up the the UCUM implementation I was under the impression. that we simply needed to fix a few small bugs and add a few missing units. Only now I realize that the whole architecture of this project is inadequate to support UCUM.

But @magnonasc has gained a lot of good experience working with units of measurements, and @keilw I think you for working with him and letting him be a part of the project.

For now, I don't care if we remove STERE or even make the whole library a series of `if` statements or whatever. I just need a JSR-363 interface to get me by with basic units that gives the correct answers without broken unit tests. If we find or write a better implementation later, we can swap it out with a different JSR 363 implementation in the future.

So all I ask is that whatever approach you take is transparent to the consuming code, and allows the consumer to simply use JSR 363, agnostic to the implementation.

In any case, I'm going to have to pull @magnonasc off this project at the end of this week because I have a critical priority project for him to be working on. Thanks again for letting us to contribute to the `uom-systems` project.

**Comment by garretwilson** [comment]
P.S. But in the future @keilw you will want to remove `LITER_DM3`, because as I noted [above](https://github.com/unitsofmeasurement/uom-systems/issues/82#issuecomment-295503959) it appears the UCUM thinks that `l` and `L` are synonyms, even in case-sensitive mode.

**Comment by keilw** [comment]
@garretwilson Thanks for the update. And for allowing @magnonasc to help with this module. When I removed it from the scope of uom-systems some months ago I did that for a reason because not all of it seemed mature enough and the initial approach merely borrowed from the UnitFormat implementation that works well with SI or other unit systems. STERE is not a Special Unit in `UCUM`, but it does have many special cases where units are not even supposed to use prefixex or other operations because there is no valid conversion. UCUM simplifies everything else to a multiplication or division by some factor. While depending on the implementation JSR 363 `UnitConverter `and `TransformedUnit `on top of them can be logarithmic or other conversions, too. `UCUMFormat` utilizes the `AnnotatedUnit` for the "annotation" part of UCUM, although that is not even a formal part. However, there is not a single `AnnotatedUnit` used in the `UCUM` class at the moment. On the other hand, AlternateUnit is not used by UCUMFormat today at all. I will try to factor a few of these features from EBNFUnitFormat into it, so ideally if you declare a particular type of unit that information (like a dedicated symbol) is used which currently just isn't used.

**Comment by keilw** [comment]
@garretwilson We'll think of a different approach, but currently with adjustments to the underlying units both seem to work properly. Maybe for 0.8 of uom-systems.

**Comment by garretwilson** [comment]
Can someone give me an update on this issue?

From my discussions with the UCUM people (see above), they indicate that `L` and `l` should be considered the same unit, even in case-sensitive mode.

* Does `uom-systems` consider a unit of `l` and a unit of `L` equivalent using Java `equals()`, or is there plans for doing so?
* Does `uom-systems` perform any canonicization so that if I create a unit using `L`, if I format it it will use `l`?

**Comment by keilw** [comment]
The UCUM specification is pretty clear about this in http://unitsofmeasure.org/ucum.html#iso1000
`LITER_DM3 `has all 3 representations while LITER does not have a c/i representation.  
I'm afraid we cannot fake or trick equals just for LITER vs. LITER_DM3 in this case. There is no dedicated subclass of `AbstractUnit` in the UCUM system, so these constants will never be equal I'm afraid, They have different base units

When you parse `c/s` 
```
 @Test
    public void testParseUCUMCSLowercaseLiter() {
	assertEquals(LITER_DM3, FORMAT_CS.parse("l"));
    }

    @Test
    public void testParseUCUMCSUppercaseLiter() {
	assertEquals(LITER, FORMAT_CS.parse("L"));
    }
```
or format `print`
```
   @Test
    public void testFormatUCUMPrint() {
	assertEquals("L", FORMAT_PRINT.format(UCUM.LITER));
    }
    
    @Test
    public void testFormatUCUMPrintDm3() {
	assertEquals("l", FORMAT_PRINT.format(UCUM.LITER_DM3));
    }
```
you expect two different results.
Parsing `c/i` both "L" and "l" return `LITER_DM3`. That's perfectly logical because the "other" `LITER `does not have a c/i representation. 
That's the only kind of equality that makes sense. Everything else would pervert the UCUM spec, regardless what someone may say in a forum. I doubt they'll remove one.

Check out the new[ JUnit test for Table 5](https://github.com/unitsofmeasurement/uom-systems/blob/master/ucum-java8/src/test/java/systems/uom/ucum/format/UCUMFormatTable5Test.java)
It also contains a `testEqualsLiters()` method.

In theory depending on what comes out of https://github.com/unitsofmeasurement/uom-se/issues/164, both `LITER_DM3` and `LITER` being a TransformedUnit, they could be considered equal, but right now, `LITER `is directly derived from `LITRE`, so the name attribute is "Litre", while `LITER_DM3` has no name. 
If the way it's added was able to change that, then IMO it could be possible to have `testEqualsLiters()` be reversed in a future version.

HTH,
Werner

**Comment by garretwilson** [comment]
Werner, did you read my communication with the UCUM in the link I gave earlier in this issue?

**Comment by keilw** [comment]
> The symbolic expressions of these units are different

That makes them different for comparison, but luckily TransformedUnit by definition and default never has a symbol, so the tweak in `UCUM ` adding a name "Liter" to both might allow to revisit this via  unitsofmeasurement/uom-se#164. Which is not simply about this particular case. As the two have a different base unit like the UCUM standard says here, currently TransformedUnit.equals() is rather strict and compares both the parent and converter. If they don't match which is not the case they are not equal. 
Using some "semantic" is the aim of unitsofmeasurement/uom-se#164, but we have to be extra careful. Take "second" it exists in the UCUM system twice, but nobody would like to see `SECOND.equals(SECOND_ANGLE)` suddenly to be true, just because their name attribute is identical ;-O
Without some kind of meta information unfortunately the Java language and compiler swallows the exact Quantity value, so in most cases you cannot rely on the name alone.

**Comment by garretwilson** [comment]
Werner, did you read my communication with the UCUM in the link I gave earlier in this issue? Specifically http://unitsofmeasure.org/trac/ticket/195 ?

**Comment by keilw** [comment]
Yes and while the whole thing by Gunther about "stere is the same as liter" does not really help you did bring it to a point with
>As such if a processor wants to remember the units entered by a user, for example, it will >need special processing logic to remember that l and L are really different ways to write >the same unit (even in case-sensitive mode)
The current approach matches the two lines UCUM has for them in every aspect. Parsing case-insensitive will only get the dm3 one because the LITER has no c/i representation. That is just not possible with any other mechanism like alias (which the UCUMFormat doesn't even support btw.) There are two completely different PRINT variants, also for SimpleUnitFormat and toString(). https://github.com/unitsofmeasurement/uom-systems/issues/111 helped fix a real issue that they were mathematically different due to a formula glitch, that is now resolved. And again pointing to whatever solution unitsofmeasurement/uom-se#164 might bring for a more detailed semantic comparison of units (just taking the name will not be enough) by fixing unitsofmeasurement/uom-se#164,https://github.com/unitsofmeasurement/uom-systems/issues/111 I'm going to close this issue, too.

	Quantity<Volume> oneLiter = Quantities.getQuantity(1, LITER);
	assertEquals(1d, oneLiter.to(LITER_DM3).getValue());
or
     assertEquals(LITER.getName(), LITER_DM3.getName());
That's as much equality

**Comment by keilw** [comment]
Especially for conversions this was fixed by https://github.com/unitsofmeasurement/uom-systems/issues/111. Making this a duplicate. Comparing the name also works, everything else is different.  Trying to compare a ProductUnit and a TransformedUnit are nearly impossible, but we'll try if e.g. 

	UnitConverter c1 = LITER.getConverterTo(LITER_DM3);
	UnitConverter c2 = LITER_DM3.getConverterTo(LITER);
	assertEquals(c1, c2);

could be used as a fallback scenario if the like in https://github.com/unitsofmeasurement/uom-systems/blob/master/ucum-java8/src/test/java/systems/uom/ucum/UCUMTest.java Similar to the AbstractQuantity.Equalizer solution for quantities. 
That is left to https://github.com/unitsofmeasurement/uom-se/issues/164, there's nothing more to be done here.
