### ISSUE TITLE
How to request systems and unit formats via JSR 363.

### ISSUE THREAD

**Issue by garretwilson** [unitsofmeasurement/uom-systems#95]
Earlier I said in https://github.com/unitsofmeasurement/uom-systems/issues/94#issuecomment-293047889:

> I'm surprised that you are registering "CI" and "CS". Can't multiple providers be registered? How do I know that I'm requesting a case-sensitive UCUM implementation and not a case-sensitive SI implementation, for example? I would have expected "UCUM-CI" and "UCUM-CS", with "UCUM" returning "UCUM-CS". I mean, "CS" and "CI" don't say anything about UCUM; they seem poor choices for a global registry that could have multiple measurement systems registered.

Perhaps I had a misunderstanding of `ServiceProvider.getUnitFormatService()`. I had thought that there would be a different `UnitFormatService` registered globally representing each measurement system.

But maybe the `ServerProvider` itself represents the  measurement system (such as UCUM), and `getUnitFormat(...)` provides a format _in relation` to the `ServerProvider`. In that case, "CI" or "SI" would be logical choices, as they would be in relation to the `ServerProvider` measurement system.

But that just raises another question: how then do I ask for a `ServiceProvider` for a particular type of measurement system? For example, let's say that one part of my program used UCUM, and another part used SI. I suppose I'd want one part of my program to ask for a `ServiceProvider` for SI, and another for `UCUM`. But in `ServiceProvider` I only see a way to set the global, "current" service provider. Am I forced to set a single `ServiceProvider` for the entire JVM if I rely solely on JSR 363 to get my `ServiceProvider` implementation.

**Comment by keilw** [comment]
I believe this is explained in the Spec: https://docs.google.com/document/d/12KhosAFriGCczBs6gwtJJDfg_QlANT92_lhxUWO2gCY/edit#heading=h.97f1g0g0sxsh

"CS" and "CI" are only two aliases, the others can be found in https://github.com/unitsofmeasurement/uom-systems/blob/master/ucum-java8/src/main/java/systems/uom/ucum/internal/UCUMFormatService.java

I added a default "UCUM" which retrieves the same as the default, so you won*t get null here any more. Let me know, if you think it's good or not? I understand it's a little less obvious with `ServiceProvider.current()` what you deal with, but it was very roughly modeled after https://docs.jboss.org/cdi/api/1.2/javax/enterprise/inject/spi/CDI.html except that `CDI` and `CDIProvider` were merged (JSR 354 has 2 separate elements called ServiceProvider and Bootstrap, based on @desruisseaux's input it was simplified here)
`ServiceProvider.current()` gives you the current ServiceProvider for a particular module. Each module could override this completely and call `ServiceProvider.setCurrent()`. With a similar result as https://docs.jboss.org/cdi/api/1.2/javax/enterprise/inject/spi/CDI.html#setCDIProvider(javax.enterprise.inject.spi.CDIProvider).
The ServiceProvider has no distinct getName() method, but via toString() you get a more or less pretty string representation. "UCUMServiceProvider" in the case of this provider. CDI does not even expose that, `CDI` contains a field `protected static volatile Set<CDIProvider> discoveredProviders` which subclasses could expose via a static method if they wish. We decided to do this somewhat similar to CDI but a bit more compact for the purpose of this JSR. Nevertheless the "discoveredProviders" or "availableProviders" are a collection, so you need to go through the collection in a for loop or similar to pick e.g. `UCUMServiceProvider`. In case of UCUM there are 3 providers, the `current()` one is based on the priority, so UCUM takes priority while e.g. the RI or other implementations on their own would have another current provider, at least the default one. So for a ServiceProvider like UCUMServiceProvider getUnitFormat("CI") makes perfect sense and the term "UCUM" would actually be a bit redundant for all of them. I'm not sure, if getUnitFormat("UCUM") really makes sense. There is no harm in it, but I would not go as far as to put UCUM in front of every alias.

Will close this issue here, as it is not directly related to uom-systems. Please let's contribute e.g. to https://github.com/unitsofmeasurement/uom-guide (the wider equivalent to https://github.com/unitsofmeasurement/unit-ri-userguide) to elaborate and document on these things. E.g. "Best Practices for Extension Modules" etc.

**Comment by garretwilson** [comment]
> I believe this is explained in the Spec...

Yeah so this confuses me a little more. If I read this correctly, there can be multiple systems of units (e.g. "UCUM" and "SI" as examples). Fine, that sounds great. The `ServiceProvider` allows me to select multiple systems of units. That also sounds good (except oddly I don't see a way to select a system of units by its name --- apparently I have to go through and look at the name of all the available systems of units.

But the confusing part is that apparently I as the `ServiceProvider` for a unit formatter _completely separate from the system of units_. So I could have selected "SI" as my system of units. Then could I ask the `ServiceProvider` for a `UCUM` unit formatter? Are unit formatters expected to know about multiple systems of units?

It seems that I'm asking for a unit formatter completely independent of any system. Thus I would expect the name of a unit format _that only handles UCUM_ to be named e.g. `UCUM_CI` or `UCUM_CS`.  Otherwise, how could someone make a case-sensitive formatter for SI without naming it e.g. `SI_CS`?

But now that I can get multiple units of measurements, I don't understand how multiple `ServiceProvider` instances come into this picture. You say there is a `ServiceProvider` called `UCUMServiceProvider`. But isn't UCUM a system of measurement? Would `UCUMServiceProvider` provide both a `UCUM` and an SI system of measurement, for example? This is all really confusing, I think.

So if the "thing" I'm asking to return me a unit formatter only handles UCUM, then sure the formatter can be named `"CS"` or `"CI"`, because that's relative to the "thing", which only handles "UCUM". But in this case the "thing" is the `ServiceProvider`, and if it only handles UCUM, then why does it provide different "systems of units"? Are there multiple UCUM systems of units? Are there multiple SI systems of units? I confess I am confused.

**Comment by magnonasc** [comment]
We surely have an usability problem here.. And I think we should only have the option `UCUM` as specified in JSR363, and it's not hard to do it!

We would just need to add an option to `UCUM` with the `CS` variant by default, and add a method on `UCUMFormatter` like `changeVariant(...)`.. 
The call would be for `CS` variant:
`UnitFormat unitFormat = ServiceProvider.current().getUnitFormatService().getUnitFormat("UCUM");`

for `CI` variant:
`UnitFormat unitFormat = ServiceProvider.current().getUnitFormatService().getUnitFormat("UCUM").changeVariant("CI");`

and for `PRINT` variant:
`UnitFormat unitFormat = ServiceProvider.current().getUnitFormatService().getUnitFormat("UCUM").changeVariant("PRINT");`

Then it'll be able to have an `SI` option.. What's the biggest issue on implementing it this way?

**Comment by keilw** [comment]
@magnonasc I'm afraid 
`UnitFormat unitFormat = ServiceProvider.current().getUnitFormatService().getUnitFormat("UCUM").changeVariant("CI");`
even though it sounds slightly like a "Builder Pattern" goes against the Spec and public API of JSR 363.

The whole "variant" idea is totally specific to UCUM and has no place in the Spec. `UCUMFormat.getInstance(Variant.CONTEXT_INSENSITIVE)` is the only place on an implementation level where this can be defined in a proper way. The next unit catalog may use "flavor", "kind" or whatever to distinguish different formats, in SimpleUnitFormat we also got `DEFAULT` (UTF-8 support) vs, `ASCII` only.

If `getUnitFormat("UCUM_CI")` was better, we could add this. The default "UCUM" probably irritates more than it helps, but on an API/standard level, I'm afraid that is all there is at the moment. Can't say if the notion of "property" or "meta information" etc. could make sense or if it was an overkill to the API.  There is already a suggestion https://github.com/unitsofmeasurement/unit-api/issues/40 for additional information to `UnitFormat`, but it would be more a "displayName" so that does not mean, the same string would be used as a key for UnitFormatService retrieval.
